### ISSUE TITLE
Link under Up2U logo

### ISSUE THREAD

**Issue by michzimny** [up2university/OpenEdX#2]
Clicking the Up2U logo in top left corner leads to Moodle. Is it expected? We would rather consider to be brought to the main page of OpenEdX, as it is a usual behaviour of web pages. My understanding is
also that a user chooses one of the available LMS systems, so I see no point in moving users from OpenEdX to Moodle. Do you consider to change this link?

**Comment by michzimny** [comment]
Vicente's reply: 
> The idea here is to use the fist page of MOODLE as a distributor to the other tools (The orange buttons) a Open EdX and a Poddium button should be added
> 
> But, of course, the redirection can be changed if this idea is not a good idea.

OpenEdX is rather an alternative to Moodle, so I think the link should lead to the main page of OpenEdX.

**Comment by pepeportela** [comment]
The redirection has been changed so now it redirects to your courses dashboard if you are logged in or to the main page if not.

**Comment by michzimny** [comment]
Thanks!
