### ISSUE TITLE
Cannot see OpenEdX stats in Matomo

### ISSUE THREAD

**Issue by michzimny** [up2university/OpenEdX#4]
@Dimitrispant, our Matomo code snippet is added to pages under https://openedx-up2u.teltek.es/. In my browser, I see it gets executed. However, in Matomo, I cannot see any stats. 

I chose:
* Behaviour -> Pages
* UP2U Production Instance
* date - today
* segment - OPENEDX

Could you please try to inspect why we cannot see any stats?

**Comment by Dimitrispant** [comment]
@michzimny I examined it, but I still cannot figure out why we don't see any stats. I need to examine it further.

**Comment by Dimitrispant** [comment]
@michzimny Now it's fine. I added again the websites on the matomo instance and it works as expected

**Comment by michzimny** [comment]
Thanks!
